import type { TickerInfo } from "./sp500";

export const NASDAQ100: TickerInfo[] = [
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft Corp.", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA Corp.", sector: "Technology" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { ticker: "META", name: "Meta Platforms", sector: "Communication Services" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { ticker: "GOOGL", name: "Alphabet Inc. (A)", sector: "Communication Services" },
  { ticker: "GOOG", name: "Alphabet Inc. (C)", sector: "Communication Services" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer Staples" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { ticker: "LIN", name: "Linde PLC", sector: "Materials" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials" },
  { ticker: "LRCX", name: "Lam Research Corp.", sector: "Technology" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { ticker: "KLAC", name: "KLA Corp.", sector: "Technology" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology" },
  { ticker: "MELI", name: "MercadoLibre Inc.", sector: "Consumer Discretionary" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Technology" },
  { ticker: "CEG", name: "Constellation Energy", sector: "Utilities" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { ticker: "CTAS", name: "Cintas Corp.", sector: "Industrials" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology" },
  { ticker: "ADP", name: "Automatic Data Processing", sector: "Technology" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
  { ticker: "DXCM", name: "Dexcom Inc.", sector: "Healthcare" },
  { ticker: "ASML", name: "ASML Holding NV", sector: "Technology" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer Discretionary" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer Staples" },
  { ticker: "PYPL", name: "PayPal Holdings", sector: "Technology" },
  { ticker: "PAYX", name: "Paychex Inc.", sector: "Technology" },
  { ticker: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare" },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare" },
  { ticker: "ODFL", name: "Old Dominion Freight", sector: "Industrials" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer Discretionary" },
  { ticker: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
  { ticker: "GEHC", name: "GE HealthCare Technologies", sector: "Healthcare" },
  { ticker: "EXC", name: "Exelon Corp.", sector: "Utilities" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology" },
  { ticker: "FAST", name: "Fastenal Co.", sector: "Industrials" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology" },
  { ticker: "GFS", name: "GlobalFoundries Inc.", sector: "Technology" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { ticker: "CMCSA", name: "Comcast Corp.", sector: "Communication Services" },
  { ticker: "NXPI", name: "NXP Semiconductors", sector: "Technology" },
  { ticker: "DLTR", name: "Dollar Tree Inc.", sector: "Consumer Discretionary" },
  { ticker: "EA", name: "Electronic Arts", sector: "Technology" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare" },
  { ticker: "TEAM", name: "Atlassian Corp.", sector: "Technology" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Technology" },
  { ticker: "CTSH", name: "Cognizant Technology", sector: "Technology" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Industrials" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology" },
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer Discretionary" },
  { ticker: "UBER", name: "Uber Technologies", sector: "Technology" },
  { ticker: "SBUX", name: "Starbucks Corp.", sector: "Consumer Discretionary" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples" },
  { ticker: "KHC", name: "Kraft Heinz Co.", sector: "Consumer Staples" },
  { ticker: "TTD", name: "Trade Desk Inc.", sector: "Technology" },
  { ticker: "WBA", name: "Walgreens Boots Alliance", sector: "Consumer Staples" },
  { ticker: "ANSS", name: "ANSYS Inc.", sector: "Technology" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { ticker: "TMUS", name: "T-Mobile US Inc.", sector: "Communication Services" },
  { ticker: "CDW", name: "CDW Corp.", sector: "Technology" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare" },
  { ticker: "CPRT", name: "Copart Inc.", sector: "Industrials" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology" },
  { ticker: "CSX", name: "CSX Corp.", sector: "Industrials" },
  { ticker: "ACGL", name: "Arch Capital Group", sector: "Financials" },
  { ticker: "MDB", name: "MongoDB Inc.", sector: "Technology" },
  { ticker: "ZBRA", name: "Zebra Technologies", sector: "Technology" },
  { ticker: "NDAQ", name: "Nasdaq Inc.", sector: "Financials" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials" },
  { ticker: "VRSN", name: "VeriSign Inc.", sector: "Technology" },
  { ticker: "MTCH", name: "Match Group", sector: "Communication Services" },
];
