import type { TickerInfo } from "./sp500";

export const RUSSELL2000: TickerInfo[] = [
  // Small-cap Technology
  { ticker: "ACLS", name: "Axcelis Technologies", sector: "Technology" },
  { ticker: "APPN", name: "Appian Corp.", sector: "Technology" },
  { ticker: "APPS", name: "Digital Turbine", sector: "Technology" },
  { ticker: "ARQQ", name: "Arqit Quantum Inc.", sector: "Technology" },
  { ticker: "ATNI", name: "ATN International", sector: "Technology" },
  { ticker: "BLKB", name: "Blackbaud Inc.", sector: "Technology" },
  { ticker: "CNXC", name: "Concentrix Corp.", sector: "Technology" },
  { ticker: "COHU", name: "Cohu Inc.", sector: "Technology" },
  { ticker: "CREE", name: "Wolfspeed Inc.", sector: "Technology" },
  { ticker: "CSOD", name: "Cornerstone OnDemand", sector: "Technology" },
  { ticker: "DGII", name: "Digi International", sector: "Technology" },
  { ticker: "EGAN", name: "eGain Corp.", sector: "Technology" },
  // EVERI removed: Everi Holdings taken private by Apollo Global, delisted 2024
  { ticker: "EXTR", name: "Extreme Networks", sector: "Technology" },
  { ticker: "FLNC", name: "Fluence Energy", sector: "Technology" },
  { ticker: "FORM", name: "FormFactor Inc.", sector: "Technology" },
  { ticker: "FOUR", name: "Shift4 Payments", sector: "Technology" },
  { ticker: "FRSH", name: "Freshworks Inc.", sector: "Technology" },
  { ticker: "GCMG", name: "GCM Grosvenor", sector: "Technology" },
  { ticker: "HLIT", name: "Harmonic Inc.", sector: "Technology" },
  { ticker: "ICUI", name: "ICU Medical Inc.", sector: "Technology" },
  { ticker: "IIIV", name: "i3 Verticals", sector: "Technology" },
  { ticker: "INMD", name: "InMode Ltd.", sector: "Technology" },
  { ticker: "INTA", name: "Intapp Inc.", sector: "Technology" },
  { ticker: "IOVA", name: "Iovance Biotherapeutics", sector: "Technology" },
  { ticker: "JAMF", name: "Jamf Holding Corp.", sector: "Technology" },
  { ticker: "KFRC", name: "Kforce Inc.", sector: "Technology" },
  { ticker: "LPSN", name: "LivePerson Inc.", sector: "Technology" },
  { ticker: "LUNA", name: "Luna Innovations", sector: "Technology" },
  { ticker: "NTNX", name: "Nutanix Inc.", sector: "Technology" },
  { ticker: "ONTO", name: "Onto Innovation Inc.", sector: "Technology" },
  { ticker: "PAGS", name: "PagSeguro Digital", sector: "Technology" },
  { ticker: "POWI", name: "Power Integrations", sector: "Technology" },
  { ticker: "PRGS", name: "Progress Software", sector: "Technology" },
  { ticker: "QLYS", name: "Qualys Inc.", sector: "Technology" },
  { ticker: "RKLB", name: "Rocket Lab USA", sector: "Technology" },
  { ticker: "SMTC", name: "Semtech Corp.", sector: "Technology" },
  { ticker: "SPSC", name: "SPS Commerce", sector: "Technology" },
  { ticker: "TNET", name: "TriNet Group", sector: "Technology" },
  { ticker: "TTGT", name: "TechTarget Inc.", sector: "Technology" },
  { ticker: "UPST", name: "Upstart Holdings", sector: "Technology" },
  { ticker: "VIAV", name: "Viavi Solutions", sector: "Technology" },
  { ticker: "XPEL", name: "XPEL Inc.", sector: "Technology" },
  // Small-cap Healthcare
  { ticker: "ACAD", name: "ACADIA Pharmaceuticals", sector: "Healthcare" },
  { ticker: "ACMR", name: "ACM Research", sector: "Healthcare" },
  { ticker: "AMED", name: "Amedisys Inc.", sector: "Healthcare" },
  { ticker: "AMPH", name: "Amphastar Pharmaceuticals", sector: "Healthcare" },
  { ticker: "ANIK", name: "Anika Therapeutics", sector: "Healthcare" },
  { ticker: "ARWR", name: "Arrowhead Pharmaceuticals", sector: "Healthcare" },
  { ticker: "ARVN", name: "Arvinas Inc.", sector: "Healthcare" },
  { ticker: "ASTH", name: "Astrana Health", sector: "Healthcare" },
  { ticker: "ATRC", name: "AtriCure Inc.", sector: "Healthcare" },
  { ticker: "AXSM", name: "Axsome Therapeutics", sector: "Healthcare" },
  { ticker: "BCPC", name: "Balchem Corp.", sector: "Healthcare" },
  { ticker: "BYND", name: "Beyond Meat Inc.", sector: "Healthcare" },
  { ticker: "CALT", name: "Calliditas Therapeutics", sector: "Healthcare" },
  { ticker: "CCXI", name: "ChemoCentryx Inc.", sector: "Healthcare" },
  { ticker: "CHRD", name: "Chord Energy Corp.", sector: "Healthcare" },
  { ticker: "CPRX", name: "Catalyst Pharmaceuticals", sector: "Healthcare" },
  { ticker: "CRVS", name: "Corvus Pharmaceuticals", sector: "Healthcare" },
  { ticker: "CTLT", name: "Catalent Inc.", sector: "Healthcare" },
  { ticker: "EHAB", name: "Enhabit Inc.", sector: "Healthcare" },
  { ticker: "ENSG", name: "Ensign Group", sector: "Healthcare" },
  { ticker: "EXAS", name: "Exact Sciences", sector: "Healthcare" },
  { ticker: "FDMT", name: "4D Molecular Therapeutics", sector: "Healthcare" },
  { ticker: "FOLD", name: "Amicus Therapeutics", sector: "Healthcare" },
  { ticker: "GKOS", name: "Glaukos Corp.", sector: "Healthcare" },
  { ticker: "GMED", name: "Globus Medical", sector: "Healthcare" },
  { ticker: "HALO", name: "Halozyme Therapeutics", sector: "Healthcare" },
  { ticker: "HIMS", name: "Hims & Hers Health", sector: "Healthcare" },
  { ticker: "HRMY", name: "Harmony Biosciences", sector: "Healthcare" },
  { ticker: "INVA", name: "Innoviva Inc.", sector: "Healthcare" },
  { ticker: "ITGR", name: "Integer Holdings", sector: "Healthcare" },
  { ticker: "KROS", name: "Keros Therapeutics", sector: "Healthcare" },
  { ticker: "LHCG", name: "LHC Group Inc.", sector: "Healthcare" },
  { ticker: "LMAT", name: "LeMaitre Vascular", sector: "Healthcare" },
  { ticker: "MDXG", name: "MiMedx Group", sector: "Healthcare" },
  { ticker: "MGNX", name: "MacroGenics Inc.", sector: "Healthcare" },
  { ticker: "MNKD", name: "MannKind Corp.", sector: "Healthcare" },
  { ticker: "NKTR", name: "Nektar Therapeutics", sector: "Healthcare" },
  { ticker: "NVCR", name: "NovaCure Ltd.", sector: "Healthcare" },
  { ticker: "OMCL", name: "Omnicell Inc.", sector: "Healthcare" },
  { ticker: "OPCH", name: "Option Care Health", sector: "Healthcare" },
  { ticker: "PCRX", name: "Pacira BioSciences", sector: "Healthcare" },
  { ticker: "PDCO", name: "Patterson Companies", sector: "Healthcare" },
  { ticker: "PRTA", name: "Prothena Corp.", sector: "Healthcare" },
  { ticker: "PTGX", name: "Protagonist Therapeutics", sector: "Healthcare" },
  { ticker: "RNST", name: "Renasant Corp.", sector: "Healthcare" },
  { ticker: "SAGE", name: "Sage Therapeutics", sector: "Healthcare" },
  { ticker: "SDGR", name: "Schrödinger Inc.", sector: "Healthcare" },
  { ticker: "TNDM", name: "Tandem Diabetes Care", sector: "Healthcare" },
  // Small-cap Financials
  { ticker: "BANF", name: "BancFirst Corp.", sector: "Financials" },
  { ticker: "BCAL", name: "Southern California Bancorp", sector: "Financials" },
  { ticker: "BSVN", name: "Bank7 Corp.", sector: "Financials" },
  { ticker: "BWFG", name: "Bankwell Financial Group", sector: "Financials" },
  { ticker: "CADE", name: "Cadence Bank", sector: "Financials" },
  { ticker: "CBTX", name: "CommunityBank of Texas", sector: "Financials" },
  { ticker: "CCFN", name: "CCFNB Corp.", sector: "Financials" },
  { ticker: "CHCO", name: "City Holding Co.", sector: "Financials" },
  { ticker: "CLBK", name: "Columbia Financial", sector: "Financials" },
  { ticker: "CNOB", name: "ConnectOne Bancorp", sector: "Financials" },
  { ticker: "COFS", name: "ChoiceOne Financial", sector: "Financials" },
  { ticker: "COLB", name: "Columbia Banking System", sector: "Financials" },
  { ticker: "CVBF", name: "CVB Financial Corp.", sector: "Financials" },
  { ticker: "DCOM", name: "Dime Community Bancshares", sector: "Financials" },
  { ticker: "EFTS", name: "EFT Payments", sector: "Financials" },
  { ticker: "ENVA", name: "Enova International", sector: "Financials" },
  { ticker: "EWBC", name: "East West Bancorp", sector: "Financials" },
  { ticker: "FFIN", name: "Cullen/Frost Bankers", sector: "Financials" },
  { ticker: "FLIC", name: "First of Long Island", sector: "Financials" },
  { ticker: "FMAO", name: "Farmers & Merchants", sector: "Financials" },
  { ticker: "FULT", name: "Fulton Financial", sector: "Financials" },
  { ticker: "GABC", name: "German American Bancorp", sector: "Financials" },
  { ticker: "GBCI", name: "Glacier Bancorp", sector: "Financials" },
  { ticker: "GNTY", name: "Guaranty Bancshares", sector: "Financials" },
  { ticker: "IBCP", name: "Independent Bank Corp.", sector: "Financials" },
  { ticker: "IBTX", name: "Independent Bank Group", sector: "Financials" },
  { ticker: "LKFN", name: "Lakeland Financial", sector: "Financials" },
  { ticker: "MCBC", name: "Mackinac Savings Bank", sector: "Financials" },
  { ticker: "NBTB", name: "NBT Bancorp", sector: "Financials" },
  { ticker: "NFBK", name: "Northfield Bancorp", sector: "Financials" },
  { ticker: "NMRK", name: "Newmark Group", sector: "Financials" },
  { ticker: "PEBO", name: "Peoples Bancorp", sector: "Financials" },
  { ticker: "PFIS", name: "Peoples Financial Services", sector: "Financials" },
  { ticker: "PRAA", name: "PRA Group Inc.", sector: "Financials" },
  { ticker: "SFBS", name: "ServisFirst Bancshares", sector: "Financials" },
  { ticker: "SFNC", name: "Simmons First National", sector: "Financials" },
  { ticker: "SMBC", name: "Southern Missouri Bancorp", sector: "Financials" },
  { ticker: "SSB", name: "SouthState Corp.", sector: "Financials" },
  { ticker: "STBA", name: "S&T Bancorp", sector: "Financials" },
  { ticker: "TBK", name: "Triumph Financial", sector: "Financials" },
  { ticker: "TOWN", name: "TowneBank Corp.", sector: "Financials" },
  { ticker: "TRMK", name: "Trustmark Corp.", sector: "Financials" },
  { ticker: "UMPQ", name: "Umpqua Holdings", sector: "Financials" },
  { ticker: "UVSP", name: "Univest Financial", sector: "Financials" },
  { ticker: "WAL", name: "Western Alliance Bancorp", sector: "Financials" },
  { ticker: "WSBC", name: "WesBanco Inc.", sector: "Financials" },
  // Small-cap Industrials
  { ticker: "ACVA", name: "ACV Auctions", sector: "Industrials" },
  // AIRC removed: Apartment Income REIT Corp ticker inactive/delisted
  { ticker: "ASTE", name: "Astec Industries", sector: "Industrials" },
  { ticker: "ATSG", name: "Air Transport Services", sector: "Industrials" },
  { ticker: "AZEK", name: "AZEK Co.", sector: "Industrials" },
  { ticker: "BFAM", name: "Bright Horizons Family", sector: "Industrials" },
  { ticker: "BLD", name: "TopBuild Corp.", sector: "Industrials" },
  { ticker: "BLDR", name: "Builders FirstSource", sector: "Industrials" },
  { ticker: "BMI", name: "Badger Meter Inc.", sector: "Industrials" },
  { ticker: "BOWX", name: "BoWX Acquisition Corp.", sector: "Industrials" },
  { ticker: "CEVA", name: "CEVA Inc.", sector: "Industrials" },
  { ticker: "CHPT", name: "ChargePoint Holdings", sector: "Industrials" },
  { ticker: "CNX", name: "CNX Resources", sector: "Industrials" },
  { ticker: "CWCO", name: "Consolidated Water Co.", sector: "Industrials" },
  { ticker: "DXPE", name: "DXP Enterprises", sector: "Industrials" },
  { ticker: "EBC", name: "Eastern Bankshares", sector: "Industrials" },
  { ticker: "ECVT", name: "Ecovyst Inc.", sector: "Industrials" },
  { ticker: "EE", name: "Excelerate Energy", sector: "Industrials" },
  { ticker: "ERII", name: "Energy Recovery Inc.", sector: "Industrials" },
  { ticker: "ESAB", name: "ESAB Corp.", sector: "Industrials" },
  { ticker: "GTES", name: "Gates Industrial Corp.", sector: "Industrials" },
  { ticker: "HCCI", name: "Heritage Crystal Clean", sector: "Industrials" },
  { ticker: "HHH", name: "Howard Hughes Holdings", sector: "Industrials" },
  { ticker: "HLIO", name: "Helios Technologies", sector: "Industrials" },
  { ticker: "HWM", name: "Howmet Aerospace", sector: "Industrials" },
  { ticker: "ITRN", name: "Ituran Location & Control", sector: "Industrials" },
  { ticker: "JOBY", name: "Joby Aviation", sector: "Industrials" },
  { ticker: "KFY", name: "Korn Ferry", sector: "Industrials" },
  { ticker: "KMPR", name: "Kemper Corp.", sector: "Industrials" },
  { ticker: "LBRT", name: "Liberty Energy Inc.", sector: "Industrials" },
  { ticker: "LMB", name: "Limbach Holdings", sector: "Industrials" },
  { ticker: "MGRC", name: "McGrath RentCorp", sector: "Industrials" },
  { ticker: "MMS", name: "Maximus Inc.", sector: "Industrials" },
  { ticker: "MRCY", name: "Mercury Systems", sector: "Industrials" },
  { ticker: "MTX", name: "Minerals Technologies", sector: "Industrials" },
  { ticker: "NBTB", name: "NBT Bancorp", sector: "Industrials" },
  { ticker: "OII", name: "Oceaneering International", sector: "Industrials" },
  { ticker: "ROAD", name: "Construction Partners", sector: "Industrials" },
  { ticker: "RNGR", name: "Ranger Energy Services", sector: "Industrials" },
  { ticker: "RXO", name: "RXO Inc.", sector: "Industrials" },
  { ticker: "SHO", name: "Sunstone Hotel Investors", sector: "Industrials" },
  { ticker: "SPXC", name: "SPX Technologies", sector: "Industrials" },
  { ticker: "STNG", name: "Scorpio Tankers", sector: "Industrials" },
  { ticker: "TREX", name: "Trex Co.", sector: "Industrials" },
  { ticker: "UHAL", name: "U-Haul Holding Co.", sector: "Industrials" },
  { ticker: "VICR", name: "Vicor Corp.", sector: "Industrials" },
  { ticker: "WGO", name: "Winnebago Industries", sector: "Industrials" },
  { ticker: "WLDN", name: "Willdan Group", sector: "Industrials" },
  // Small-cap Consumer
  { ticker: "ARCO", name: "Arcos Dorados Holdings", sector: "Consumer Discretionary" },
  { ticker: "BOOT", name: "Boot Barn Holdings", sector: "Consumer Discretionary" },
  { ticker: "CAKE", name: "Cheesecake Factory", sector: "Consumer Discretionary" },
  { ticker: "CHUY", name: "Chuy's Holdings", sector: "Consumer Discretionary" },
  { ticker: "COUR", name: "Coursera Inc.", sector: "Consumer Discretionary" },
  { ticker: "CRVL", name: "CorVel Corp.", sector: "Consumer Discretionary" },
  { ticker: "DRVN", name: "Driven Brands Holdings", sector: "Consumer Discretionary" },
  { ticker: "EAT", name: "Brinker International", sector: "Consumer Discretionary" },
  { ticker: "FUTU", name: "Futu Holdings", sector: "Consumer Discretionary" },
  { ticker: "GFF", name: "Griffon Corp.", sector: "Consumer Discretionary" },
  { ticker: "HAIN", name: "Hain Celestial Group", sector: "Consumer Staples" },
  { ticker: "JACK", name: "Jack in the Box", sector: "Consumer Discretionary" },
  { ticker: "JOANN", name: "JOANN Inc.", sector: "Consumer Discretionary" },
  { ticker: "KRUS", name: "Kura Sushi USA", sector: "Consumer Discretionary" },
  { ticker: "LGND", name: "Ligand Pharmaceuticals", sector: "Consumer Discretionary" },
  { ticker: "LOVE", name: "Lovesac Co.", sector: "Consumer Discretionary" },
  { ticker: "LUCK", name: "Lucky Strike Entertainment", sector: "Consumer Discretionary" },
  { ticker: "MGAM", name: "Multimedia Games Holding", sector: "Consumer Discretionary" },
  { ticker: "MODG", name: "Topgolf Callaway Brands", sector: "Consumer Discretionary" },
  { ticker: "MUSA", name: "Murphy USA Inc.", sector: "Consumer Staples" },
  { ticker: "NN", name: "NextNav Inc.", sector: "Consumer Discretionary" },
  { ticker: "NRDS", name: "NerdWallet Inc.", sector: "Consumer Discretionary" },
  { ticker: "OFIX", name: "Orthofix Medical", sector: "Consumer Discretionary" },
  { ticker: "PLAY", name: "Dave & Buster's", sector: "Consumer Discretionary" },
  { ticker: "PLBY", name: "PLBY Group", sector: "Consumer Discretionary" },
  { ticker: "PRPL", name: "Purple Innovation", sector: "Consumer Discretionary" },
  { ticker: "PTON", name: "Peloton Interactive", sector: "Consumer Discretionary" },
  { ticker: "RAMP", name: "LiveRamp Holdings", sector: "Consumer Discretionary" },
  { ticker: "RICK", name: "RCI Hospitality", sector: "Consumer Discretionary" },
  { ticker: "RRR", name: "Red Rock Resorts", sector: "Consumer Discretionary" },
  { ticker: "RUTH", name: "Ruth's Hospitality Group", sector: "Consumer Discretionary" },
  { ticker: "SHOO", name: "Steven Madden Ltd.", sector: "Consumer Discretionary" },
  { ticker: "SMPL", name: "Simply Good Foods", sector: "Consumer Staples" },
  { ticker: "SPCE", name: "Virgin Galactic Holdings", sector: "Consumer Discretionary" },
  { ticker: "STRA", name: "Strategic Education", sector: "Consumer Discretionary" },
  { ticker: "SWIM", name: "Latham Group", sector: "Consumer Discretionary" },
  { ticker: "TACO", name: "Del Taco Restaurants", sector: "Consumer Discretionary" },
  { ticker: "TLYS", name: "Tilly's Inc.", sector: "Consumer Discretionary" },
  { ticker: "TUEM", name: "Tuesday Morning Corp.", sector: "Consumer Discretionary" },
  { ticker: "WING", name: "Wingstop Inc.", sector: "Consumer Discretionary" },
  { ticker: "XRAY", name: "Dentsply Sirona", sector: "Healthcare" },
  // Small-cap Energy & Materials
  { ticker: "AMRC", name: "Ameresco Inc.", sector: "Energy" },
  { ticker: "ARCH", name: "Arch Resources", sector: "Materials" },
  { ticker: "AROC", name: "Archrock Inc.", sector: "Energy" },
  { ticker: "BATL", name: "Battalion Oil Corp.", sector: "Energy" },
  { ticker: "CIVI", name: "Civitas Resources", sector: "Energy" },
  { ticker: "CLR", name: "Continental Resources", sector: "Energy" },
  { ticker: "CLNE", name: "Clean Energy Fuels", sector: "Energy" },
  { ticker: "CPRI", name: "Capri Holdings", sector: "Consumer Discretionary" },
  { ticker: "DK", name: "Delek Group", sector: "Energy" },
  { ticker: "DRQ", name: "Dril-Quip Inc.", sector: "Energy" },
  { ticker: "ESTE", name: "Earthstone Energy", sector: "Energy" },
  { ticker: "FLNG", name: "FLEX LNG Ltd.", sector: "Energy" },
  { ticker: "GNE", name: "Genie Energy Ltd.", sector: "Energy" },
  { ticker: "HCC", name: "Warrior Met Coal", sector: "Materials" },
  { ticker: "HESM", name: "Hess Midstream", sector: "Energy" },
  { ticker: "KALU", name: "Kaiser Aluminum", sector: "Materials" },
  { ticker: "LTHM", name: "Livent Corp.", sector: "Materials" },
  { ticker: "MP", name: "MP Materials Corp.", sector: "Materials" },
  { ticker: "NFG", name: "National Fuel Gas", sector: "Energy" },
  { ticker: "NGL", name: "NGL Energy Partners", sector: "Energy" },
  { ticker: "OVV", name: "Ovintiv Inc.", sector: "Energy" },
  { ticker: "PTEN", name: "Patterson-UTI Energy", sector: "Energy" },
  { ticker: "REX", name: "REX Energy Corp.", sector: "Energy" },
  { ticker: "ROCC", name: "Ranger Oil Corp.", sector: "Energy" },
  { ticker: "SDRL", name: "Seadrill Ltd.", sector: "Energy" },
  { ticker: "SM", name: "SM Energy Co.", sector: "Energy" },
  { ticker: "STNG", name: "Scorpio Tankers", sector: "Energy" },
  { ticker: "SWN", name: "Southwestern Energy", sector: "Energy" },
  { ticker: "TALO", name: "Talos Energy Inc.", sector: "Energy" },
  { ticker: "TPC", name: "Tutor Perini Corp.", sector: "Industrials" },
  { ticker: "TRMD", name: "TORM PLC", sector: "Energy" },
  { ticker: "USDP", name: "USD Partners", sector: "Energy" },
  { ticker: "VAALCO", name: "Vaalco Energy", sector: "Energy" },
  { ticker: "VNOM", name: "Viper Energy Partners", sector: "Energy" },
  { ticker: "WTTR", name: "Select Water Solutions", sector: "Energy" },
  // Small-cap Real Estate
  { ticker: "AIV", name: "Apartment Investment", sector: "Real Estate" },
  { ticker: "ALEX", name: "Alexander & Baldwin", sector: "Real Estate" },
  { ticker: "BRT", name: "BRT Realty Trust", sector: "Real Estate" },
  { ticker: "CLDT", name: "Chatham Lodging Trust", sector: "Real Estate" },
  { ticker: "CTRE", name: "CareTrust REIT", sector: "Real Estate" },
  { ticker: "DEA", name: "Easterly Government", sector: "Real Estate" },
  { ticker: "EFC", name: "Ellington Financial", sector: "Real Estate" },
  { ticker: "GMRE", name: "Global Medical REIT", sector: "Real Estate" },
  { ticker: "GOOD", name: "Gladstone Commercial", sector: "Real Estate" },
  { ticker: "GTY", name: "Getty Realty Corp.", sector: "Real Estate" },
  { ticker: "IIPR", name: "Innovative Industrial Prop.", sector: "Real Estate" },
  { ticker: "INDUS", name: "Indus Realty Trust", sector: "Real Estate" },
  { ticker: "JBGS", name: "JBG SMITH Properties", sector: "Real Estate" },
  { ticker: "LXP", name: "LXP Industrial Trust", sector: "Real Estate" },
  { ticker: "NLCP", name: "NewLake Capital Partners", sector: "Real Estate" },
  { ticker: "NTST", name: "NETSTREIT Corp.", sector: "Real Estate" },
  { ticker: "PDM", name: "Piedmont Office Realty", sector: "Real Estate" },
  { ticker: "RHP", name: "Ryman Hospitality", sector: "Real Estate" },
  { ticker: "RICK", name: "RCI Hospitality", sector: "Real Estate" },
  { ticker: "SAFE", name: "iStar Inc.", sector: "Real Estate" },
  { ticker: "SHO", name: "Sunstone Hotel Investors", sector: "Real Estate" },
  { ticker: "STAG", name: "STAG Industrial", sector: "Real Estate" },
  { ticker: "STOR", name: "STORE Capital Corp.", sector: "Real Estate" },
  { ticker: "UE", name: "Urban Edge Properties", sector: "Real Estate" },
  { ticker: "UNITY", name: "Unity Software", sector: "Technology" },
  { ticker: "WHLR", name: "Wheeler REIT", sector: "Real Estate" },
  { ticker: "XHR", name: "Xenia Hotels & Resorts", sector: "Real Estate" },
];
