export interface TickerInfo { ticker: string; name: string; sector: string }

export const SP500: TickerInfo[] = [
  // Technology
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft Corp.", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA Corp.", sector: "Technology" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { ticker: "ORCL", name: "Oracle Corp.", sector: "Technology" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology" },
  { ticker: "ACN", name: "Accenture PLC", sector: "Technology" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology" },
  { ticker: "IBM", name: "IBM Corp.", sector: "Technology" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology" },
  { ticker: "LRCX", name: "Lam Research Corp.", sector: "Technology" },
  { ticker: "KLAC", name: "KLA Corp.", sector: "Technology" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { ticker: "APH", name: "Amphenol Corp.", sector: "Technology" },
  { ticker: "KEYS", name: "Keysight Technologies", sector: "Technology" },
  { ticker: "ANSS", name: "ANSYS Inc.", sector: "Technology" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
  { ticker: "WDC", name: "Western Digital", sector: "Technology" },
  { ticker: "HPQ", name: "HP Inc.", sector: "Technology" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology" },
  { ticker: "STX", name: "Seagate Technology", sector: "Technology" },
  { ticker: "NTAP", name: "NetApp Inc.", sector: "Technology" },
  { ticker: "IT", name: "Gartner Inc.", sector: "Technology" },
  { ticker: "CDW", name: "CDW Corp.", sector: "Technology" },
  { ticker: "PTC", name: "PTC Inc.", sector: "Technology" },
  { ticker: "FSLR", name: "First Solar Inc.", sector: "Technology" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology" },
  { ticker: "AKAM", name: "Akamai Technologies", sector: "Technology" },
  { ticker: "MPWR", name: "Monolithic Power Systems", sector: "Technology" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology" },
  { ticker: "ZBRA", name: "Zebra Technologies", sector: "Technology" },
  { ticker: "GLW", name: "Corning Inc.", sector: "Technology" },
  { ticker: "VRSN", name: "VeriSign Inc.", sector: "Technology" },
  { ticker: "TER", name: "Teradyne Inc.", sector: "Technology" },
  { ticker: "TRMB", name: "Trimble Inc.", sector: "Technology" },
  { ticker: "EA", name: "Electronic Arts", sector: "Technology" },
  { ticker: "LDOS", name: "Leidos Holdings", sector: "Technology" },
  { ticker: "CTSH", name: "Cognizant Technology", sector: "Technology" },
  { ticker: "JNPR", name: "Juniper Networks", sector: "Technology" },
  { ticker: "GPN", name: "Global Payments", sector: "Technology" },
  { ticker: "PAYX", name: "Paychex Inc.", sector: "Technology" },
  { ticker: "ADP", name: "Automatic Data Processing", sector: "Technology" },
  { ticker: "FISV", name: "Fiserv Inc.", sector: "Technology" },
  { ticker: "FIS", name: "Fidelity National Info", sector: "Technology" },
  { ticker: "MSCI", name: "MSCI Inc.", sector: "Technology" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Technology" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology" },
  { ticker: "GDDY", name: "GoDaddy Inc.", sector: "Technology" },
  { ticker: "EPAM", name: "EPAM Systems", sector: "Technology" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Technology" },
  // Communication Services
  { ticker: "META", name: "Meta Platforms", sector: "Communication Services" },
  { ticker: "GOOGL", name: "Alphabet Inc. (A)", sector: "Communication Services" },
  { ticker: "GOOG", name: "Alphabet Inc. (C)", sector: "Communication Services" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { ticker: "DIS", name: "Walt Disney Co.", sector: "Communication Services" },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { ticker: "CMCSA", name: "Comcast Corp.", sector: "Communication Services" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Communication Services" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { ticker: "TMUS", name: "T-Mobile US Inc.", sector: "Communication Services" },
  { ticker: "FOXA", name: "Fox Corp. (A)", sector: "Communication Services" },
  { ticker: "FOX", name: "Fox Corp. (B)", sector: "Communication Services" },
  { ticker: "OMC", name: "Omnicom Group", sector: "Communication Services" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services" },
  { ticker: "LYV", name: "Live Nation Entertainment", sector: "Communication Services" },
  { ticker: "NWSA", name: "News Corp (A)", sector: "Communication Services" },
  { ticker: "NWS", name: "News Corp (B)", sector: "Communication Services" },
  { ticker: "MTCH", name: "Match Group", sector: "Communication Services" },
  // PARA removed: Paramount Global acquired by Skydance Media, delisted Jan 2025
  { ticker: "IPG", name: "Interpublic Group", sector: "Communication Services" },
  // Consumer Discretionary
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { ticker: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary" },
  { ticker: "MCD", name: "McDonald's Corp.", sector: "Consumer Discretionary" },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary" },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer Discretionary" },
  { ticker: "SBUX", name: "Starbucks Corp.", sector: "Consumer Discretionary" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { ticker: "TGT", name: "Target Corp.", sector: "Consumer Discretionary" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { ticker: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { ticker: "F", name: "Ford Motor Co.", sector: "Consumer Discretionary" },
  { ticker: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer Discretionary" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer Discretionary" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary" },
  { ticker: "APTV", name: "Aptiv PLC", sector: "Consumer Discretionary" },
  { ticker: "DHI", name: "D.R. Horton Inc.", sector: "Consumer Discretionary" },
  { ticker: "LEN", name: "Lennar Corp.", sector: "Consumer Discretionary" },
  { ticker: "PHM", name: "PulteGroup Inc.", sector: "Consumer Discretionary" },
  { ticker: "NVR", name: "NVR Inc.", sector: "Consumer Discretionary" },
  { ticker: "TOL", name: "Toll Brothers Inc.", sector: "Consumer Discretionary" },
  { ticker: "PVH", name: "PVH Corp.", sector: "Consumer Discretionary" },
  { ticker: "HAS", name: "Hasbro Inc.", sector: "Consumer Discretionary" },
  { ticker: "MHK", name: "Mohawk Industries", sector: "Consumer Discretionary" },
  { ticker: "WHR", name: "Whirlpool Corp.", sector: "Consumer Discretionary" },
  { ticker: "RL", name: "Ralph Lauren Corp.", sector: "Consumer Discretionary" },
  { ticker: "TPR", name: "Tapestry Inc.", sector: "Consumer Discretionary" },
  { ticker: "GRMN", name: "Garmin Ltd.", sector: "Consumer Discretionary" },
  { ticker: "EXPE", name: "Expedia Group", sector: "Consumer Discretionary" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { ticker: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
  { ticker: "BBY", name: "Best Buy Co.", sector: "Consumer Discretionary" },
  { ticker: "DG", name: "Dollar General Corp.", sector: "Consumer Discretionary" },
  { ticker: "DLTR", name: "Dollar Tree Inc.", sector: "Consumer Discretionary" },
  { ticker: "DKNG", name: "DraftKings Inc.", sector: "Consumer Discretionary" },
  { ticker: "WYNN", name: "Wynn Resorts", sector: "Consumer Discretionary" },
  { ticker: "LVS", name: "Las Vegas Sands", sector: "Consumer Discretionary" },
  { ticker: "MGM", name: "MGM Resorts", sector: "Consumer Discretionary" },
  { ticker: "CCL", name: "Carnival Corp.", sector: "Consumer Discretionary" },
  { ticker: "RCL", name: "Royal Caribbean Group", sector: "Consumer Discretionary" },
  { ticker: "NCLH", name: "Norwegian Cruise Line", sector: "Consumer Discretionary" },
  { ticker: "POOL", name: "Pool Corp.", sector: "Consumer Discretionary" },
  { ticker: "WSM", name: "Williams-Sonoma", sector: "Consumer Discretionary" },
  { ticker: "LKQ", name: "LKQ Corp.", sector: "Consumer Discretionary" },
  { ticker: "BWA", name: "BorgWarner Inc.", sector: "Consumer Discretionary" },
  { ticker: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary" },
  { ticker: "ETSY", name: "Etsy Inc.", sector: "Consumer Discretionary" },
  { ticker: "GPC", name: "Genuine Parts Co.", sector: "Consumer Discretionary" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Consumer Discretionary" },
  // Consumer Staples
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { ticker: "KO", name: "Coca-Cola Co.", sector: "Consumer Staples" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer Staples" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { ticker: "MO", name: "Altria Group", sector: "Consumer Staples" },
  { ticker: "EL", name: "Estee Lauder Companies", sector: "Consumer Staples" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { ticker: "KHC", name: "Kraft Heinz Co.", sector: "Consumer Staples" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer Staples" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer Staples" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples" },
  { ticker: "HSY", name: "Hershey Co.", sector: "Consumer Staples" },
  { ticker: "CAG", name: "Conagra Brands", sector: "Consumer Staples" },
  { ticker: "SJM", name: "J.M. Smucker Co.", sector: "Consumer Staples" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer Staples" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer Staples" },
  { ticker: "MKC", name: "McCormick & Co.", sector: "Consumer Staples" },
  { ticker: "BG", name: "Bunge Global", sector: "Consumer Staples" },
  { ticker: "CPB", name: "Campbell Soup Co.", sector: "Consumer Staples" },
  { ticker: "TSN", name: "Tyson Foods", sector: "Consumer Staples" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer Staples" },
  { ticker: "WBA", name: "Walgreens Boots Alliance", sector: "Consumer Staples" },
  { ticker: "CVS", name: "CVS Health Corp.", sector: "Consumer Staples" },
  { ticker: "SYY", name: "Sysco Corp.", sector: "Consumer Staples" },
  { ticker: "TAP", name: "Molson Coors Beverage", sector: "Consumer Staples" },
  { ticker: "USFD", name: "US Foods Holding", sector: "Consumer Staples" },
  { ticker: "CLX", name: "Clorox Co.", sector: "Consumer Staples" },
  // Healthcare
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { ticker: "LLY", name: "Eli Lilly and Co.", sector: "Healthcare" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck & Co.", sector: "Healthcare" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { ticker: "SYK", name: "Stryker Corp.", sector: "Healthcare" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { ticker: "MDT", name: "Medtronic PLC", sector: "Healthcare" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Healthcare" },
  { ticker: "BDX", name: "Becton Dickinson", sector: "Healthcare" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { ticker: "ZBH", name: "Zimmer Biomet Holdings", sector: "Healthcare" },
  { ticker: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare" },
  { ticker: "IQV", name: "IQVIA Holdings", sector: "Healthcare" },
  { ticker: "MCK", name: "McKesson Corp.", sector: "Healthcare" },
  { ticker: "ABC", name: "AmerisourceBergen", sector: "Healthcare" },
  { ticker: "CAH", name: "Cardinal Health", sector: "Healthcare" },
  { ticker: "HCA", name: "HCA Healthcare", sector: "Healthcare" },
  { ticker: "CNC", name: "Centene Corp.", sector: "Healthcare" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { ticker: "HUM", name: "Humana Inc.", sector: "Healthcare" },
  { ticker: "MOH", name: "Molina Healthcare", sector: "Healthcare" },
  { ticker: "DVA", name: "DaVita Inc.", sector: "Healthcare" },
  { ticker: "HOLX", name: "Hologic Inc.", sector: "Healthcare" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare" },
  { ticker: "TFX", name: "Teleflex Inc.", sector: "Healthcare" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare" },
  { ticker: "COO", name: "Cooper Companies", sector: "Healthcare" },
  { ticker: "RMD", name: "ResMed Inc.", sector: "Healthcare" },
  { ticker: "PODD", name: "Insulet Corp.", sector: "Healthcare" },
  { ticker: "AVTR", name: "Avantor Inc.", sector: "Healthcare" },
  { ticker: "MTD", name: "Mettler-Toledo", sector: "Healthcare" },
  { ticker: "WAT", name: "Waters Corp.", sector: "Healthcare" },
  { ticker: "A", name: "Agilent Technologies", sector: "Healthcare" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { ticker: "DXCM", name: "Dexcom Inc.", sector: "Healthcare" },
  { ticker: "INCY", name: "Incyte Corp.", sector: "Healthcare" },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare" },
  { ticker: "VEEV", name: "Veeva Systems", sector: "Healthcare" },
  { ticker: "VTRS", name: "Viatris Inc.", sector: "Healthcare" },
  { ticker: "BAX", name: "Baxter International", sector: "Healthcare" },
  { ticker: "PKI", name: "PerkinElmer Inc.", sector: "Healthcare" },
  // Financials
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { ticker: "BAC", name: "Bank of America", sector: "Financials" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Financials" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financials" },
  { ticker: "AXP", name: "American Express", sector: "Financials" },
  { ticker: "SPGI", name: "S&P Global Inc.", sector: "Financials" },
  { ticker: "COF", name: "Capital One Financial", sector: "Financials" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Financials" },
  { ticker: "TFC", name: "Truist Financial", sector: "Financials" },
  { ticker: "MCO", name: "Moody's Corp.", sector: "Financials" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { ticker: "CME", name: "CME Group Inc.", sector: "Financials" },
  { ticker: "CB", name: "Chubb Ltd.", sector: "Financials" },
  { ticker: "MMC", name: "Marsh & McLennan", sector: "Financials" },
  { ticker: "AON", name: "Aon PLC", sector: "Financials" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Financials" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Financials" },
  { ticker: "AFL", name: "Aflac Inc.", sector: "Financials" },
  { ticker: "ALL", name: "Allstate Corp.", sector: "Financials" },
  { ticker: "AIG", name: "American International Group", sector: "Financials" },
  { ticker: "HIG", name: "Hartford Financial Services", sector: "Financials" },
  { ticker: "BK", name: "Bank of New York Mellon", sector: "Financials" },
  { ticker: "STT", name: "State Street Corp.", sector: "Financials" },
  { ticker: "KEY", name: "KeyCorp", sector: "Financials" },
  { ticker: "RF", name: "Regions Financial", sector: "Financials" },
  { ticker: "CFG", name: "Citizens Financial Group", sector: "Financials" },
  { ticker: "FITB", name: "Fifth Third Bancorp", sector: "Financials" },
  { ticker: "HBAN", name: "Huntington Bancshares", sector: "Financials" },
  { ticker: "MTB", name: "M&T Bank Corp.", sector: "Financials" },
  { ticker: "RJF", name: "Raymond James Financial", sector: "Financials" },
  { ticker: "LNC", name: "Lincoln National", sector: "Financials" },
  { ticker: "NDAQ", name: "Nasdaq Inc.", sector: "Financials" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Financials" },
  { ticker: "TROW", name: "T. Rowe Price Group", sector: "Financials" },
  { ticker: "IVZ", name: "Invesco Ltd.", sector: "Financials" },
  { ticker: "NTRS", name: "Northern Trust Corp.", sector: "Financials" },
  { ticker: "SEIC", name: "SEI Investments", sector: "Financials" },
  { ticker: "FDS", name: "FactSet Research Systems", sector: "Financials" },
  { ticker: "CINF", name: "Cincinnati Financial", sector: "Financials" },
  { ticker: "GL", name: "Globe Life Inc.", sector: "Financials" },
  { ticker: "WRB", name: "W.R. Berkley Corp.", sector: "Financials" },
  { ticker: "SFG", name: "StonePoint Capital Group", sector: "Financials" },
  // Industrials
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials" },
  { ticker: "RTX", name: "RTX Corp.", sector: "Industrials" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { ticker: "BA", name: "Boeing Co.", sector: "Industrials" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrials" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrials" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { ticker: "FDX", name: "FedEx Corp.", sector: "Industrials" },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials" },
  { ticker: "MMM", name: "3M Co.", sector: "Industrials" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials" },
  { ticker: "ETN", name: "Eaton Corp.", sector: "Industrials" },
  { ticker: "PH", name: "Parker-Hannifin Corp.", sector: "Industrials" },
  { ticker: "ROP", name: "Roper Technologies", sector: "Industrials" },
  { ticker: "AME", name: "AMETEK Inc.", sector: "Industrials" },
  { ticker: "XYL", name: "Xylem Inc.", sector: "Industrials" },
  { ticker: "PWR", name: "Quanta Services", sector: "Industrials" },
  { ticker: "CARR", name: "Carrier Global", sector: "Industrials" },
  { ticker: "OTIS", name: "Otis Worldwide", sector: "Industrials" },
  { ticker: "JCI", name: "Johnson Controls", sector: "Industrials" },
  { ticker: "TT", name: "Trane Technologies", sector: "Industrials" },
  { ticker: "SWK", name: "Stanley Black & Decker", sector: "Industrials" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials" },
  { ticker: "IEX", name: "IDEX Corp.", sector: "Industrials" },
  { ticker: "MAS", name: "Masco Corp.", sector: "Industrials" },
  { ticker: "WAB", name: "Wabtec Corp.", sector: "Industrials" },
  { ticker: "GWW", name: "W.W. Grainger", sector: "Industrials" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
  { ticker: "CMI", name: "Cummins Inc.", sector: "Industrials" },
  { ticker: "CTAS", name: "Cintas Corp.", sector: "Industrials" },
  { ticker: "RSG", name: "Republic Services", sector: "Industrials" },
  { ticker: "WM", name: "Waste Management", sector: "Industrials" },
  { ticker: "EFX", name: "Equifax Inc.", sector: "Industrials" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Industrials" },
  { ticker: "CPRT", name: "Copart Inc.", sector: "Industrials" },
  { ticker: "EXPD", name: "Expeditors International", sector: "Industrials" },
  { ticker: "CHRW", name: "C.H. Robinson Worldwide", sector: "Industrials" },
  { ticker: "FAST", name: "Fastenal Co.", sector: "Industrials" },
  { ticker: "URI", name: "United Rentals", sector: "Industrials" },
  { ticker: "PAYC", name: "Paycom Software", sector: "Industrials" },
  { ticker: "JBHT", name: "J.B. Hunt Transport", sector: "Industrials" },
  { ticker: "ODFL", name: "Old Dominion Freight", sector: "Industrials" },
  { ticker: "XPO", name: "XPO Inc.", sector: "Industrials" },
  { ticker: "SAIA", name: "Saia Inc.", sector: "Industrials" },
  { ticker: "GXO", name: "GXO Logistics", sector: "Industrials" },
  { ticker: "AXON", name: "Axon Enterprise", sector: "Industrials" },
  { ticker: "BAH", name: "Booz Allen Hamilton", sector: "Industrials" },
  { ticker: "CSX", name: "CSX Corp.", sector: "Industrials" },
  { ticker: "UNP", name: "Union Pacific Corp.", sector: "Industrials" },
  { ticker: "NSC", name: "Norfolk Southern", sector: "Industrials" },
  { ticker: "UAL", name: "United Airlines Holdings", sector: "Industrials" },
  { ticker: "DAL", name: "Delta Air Lines", sector: "Industrials" },
  { ticker: "LUV", name: "Southwest Airlines", sector: "Industrials" },
  { ticker: "AAL", name: "American Airlines Group", sector: "Industrials" },
  { ticker: "ALK", name: "Alaska Air Group", sector: "Industrials" },
  { ticker: "FTV", name: "Fortive Corp.", sector: "Industrials" },
  { ticker: "HII", name: "Huntington Ingalls", sector: "Industrials" },
  { ticker: "TXT", name: "Textron Inc.", sector: "Industrials" },
  { ticker: "CW", name: "Curtiss-Wright Corp.", sector: "Industrials" },
  // Materials
  { ticker: "LIN", name: "Linde PLC", sector: "Materials" },
  { ticker: "APD", name: "Air Products & Chemicals", sector: "Materials" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials" },
  { ticker: "NEM", name: "Newmont Corp.", sector: "Materials" },
  { ticker: "NUE", name: "Nucor Corp.", sector: "Materials" },
  { ticker: "CF", name: "CF Industries Holdings", sector: "Materials" },
  { ticker: "MOS", name: "Mosaic Co.", sector: "Materials" },
  { ticker: "ECL", name: "Ecolab Inc.", sector: "Materials" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials" },
  { ticker: "IFF", name: "International Flavors", sector: "Materials" },
  { ticker: "ALB", name: "Albemarle Corp.", sector: "Materials" },
  { ticker: "EMN", name: "Eastman Chemical", sector: "Materials" },
  { ticker: "CE", name: "Celanese Corp.", sector: "Materials" },
  { ticker: "DOW", name: "Dow Inc.", sector: "Materials" },
  { ticker: "LYB", name: "LyondellBasell Industries", sector: "Materials" },
  { ticker: "BALL", name: "Ball Corp.", sector: "Materials" },
  { ticker: "PKG", name: "Packaging Corp. of America", sector: "Materials" },
  { ticker: "IP", name: "International Paper", sector: "Materials" },
  { ticker: "AVY", name: "Avery Dennison", sector: "Materials" },
  { ticker: "ATI", name: "ATI Inc.", sector: "Materials" },
  { ticker: "RS", name: "Reliance Steel & Aluminum", sector: "Materials" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials" },
  { ticker: "CMC", name: "Commercial Metals Co.", sector: "Materials" },
  { ticker: "WRK", name: "WestRock Co.", sector: "Materials" },
  { ticker: "SEE", name: "Sealed Air Corp.", sector: "Materials" },
  { ticker: "SON", name: "Sonoco Products", sector: "Materials" },
  { ticker: "RPM", name: "RPM International", sector: "Materials" },
  { ticker: "FMC", name: "FMC Corp.", sector: "Materials" },
  // Energy
  { ticker: "XOM", name: "ExxonMobil Corp.", sector: "Energy" },
  { ticker: "CVX", name: "Chevron Corp.", sector: "Energy" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy" },
  { ticker: "HES", name: "Hess Corp.", sector: "Energy" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { ticker: "HAL", name: "Halliburton Co.", sector: "Energy" },
  { ticker: "SLB", name: "SLB (Schlumberger)", sector: "Energy" },
  { ticker: "BKR", name: "Baker Hughes Co.", sector: "Energy" },
  { ticker: "MRO", name: "Marathon Oil Corp.", sector: "Energy" },
  { ticker: "APA", name: "APA Corp.", sector: "Energy" },
  { ticker: "EQT", name: "EQT Corp.", sector: "Energy" },
  { ticker: "LNG", name: "Cheniere Energy", sector: "Energy" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy" },
  { ticker: "OKE", name: "ONEOK Inc.", sector: "Energy" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { ticker: "MTDR", name: "Matador Resources", sector: "Energy" },
  { ticker: "NOV", name: "NOV Inc.", sector: "Energy" },
  { ticker: "HP", name: "Helmerich & Payne", sector: "Energy" },
  // Real Estate
  { ticker: "AMT", name: "American Tower Corp.", sector: "Real Estate" },
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
  { ticker: "CCI", name: "Crown Castle Inc.", sector: "Real Estate" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate" },
  { ticker: "AVB", name: "AvalonBay Communities", sector: "Real Estate" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate" },
  { ticker: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
  { ticker: "DLR", name: "Digital Realty Trust", sector: "Real Estate" },
  { ticker: "ESS", name: "Essex Property Trust", sector: "Real Estate" },
  { ticker: "VTR", name: "Ventas Inc.", sector: "Real Estate" },
  { ticker: "INVH", name: "Invitation Homes", sector: "Real Estate" },
  { ticker: "MAA", name: "Mid-America Apartment", sector: "Real Estate" },
  { ticker: "UDR", name: "UDR Inc.", sector: "Real Estate" },
  { ticker: "REG", name: "Regency Centers", sector: "Real Estate" },
  { ticker: "FRT", name: "Federal Realty Investment", sector: "Real Estate" },
  { ticker: "BXP", name: "BXP Inc.", sector: "Real Estate" },
  { ticker: "KIM", name: "Kimco Realty", sector: "Real Estate" },
  { ticker: "O", name: "Realty Income Corp.", sector: "Real Estate" },
  { ticker: "VICI", name: "VICI Properties", sector: "Real Estate" },
  { ticker: "IRM", name: "Iron Mountain Inc.", sector: "Real Estate" },
  { ticker: "SBAC", name: "SBA Communications", sector: "Real Estate" },
  { ticker: "CUBE", name: "CubeSmart", sector: "Real Estate" },
  { ticker: "NNN", name: "NNN REIT Inc.", sector: "Real Estate" },
  // Utilities
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { ticker: "DUK", name: "Duke Energy Corp.", sector: "Utilities" },
  { ticker: "SO", name: "Southern Co.", sector: "Utilities" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities" },
  { ticker: "EXC", name: "Exelon Corp.", sector: "Utilities" },
  { ticker: "SRE", name: "Sempra Energy", sector: "Utilities" },
  { ticker: "PCG", name: "PG&E Corp.", sector: "Utilities" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities" },
  { ticker: "PEG", name: "Public Service Enterprise", sector: "Utilities" },
  { ticker: "FE", name: "FirstEnergy Corp.", sector: "Utilities" },
  { ticker: "ETR", name: "Entergy Corp.", sector: "Utilities" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities" },
  { ticker: "DTE", name: "DTE Energy Co.", sector: "Utilities" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities" },
  { ticker: "NI", name: "NiSource Inc.", sector: "Utilities" },
  { ticker: "CNP", name: "CenterPoint Energy", sector: "Utilities" },
  { ticker: "LNT", name: "Alliant Energy", sector: "Utilities" },
  { ticker: "EVRG", name: "Evergy Inc.", sector: "Utilities" },
  { ticker: "AES", name: "AES Corp.", sector: "Utilities" },
  { ticker: "EIX", name: "Edison International", sector: "Utilities" },
  { ticker: "CMS", name: "CMS Energy Corp.", sector: "Utilities" },
  { ticker: "PPL", name: "PPL Corp.", sector: "Utilities" },
  { ticker: "ATO", name: "Atmos Energy Corp.", sector: "Utilities" },
];
